apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-react
  template:
    metadata:
      labels:
        app: myapp-react
    spec:
      containers:
      - name: myapp-container
        image: my-app-dev:v1
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
