apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react
  template:
    metadata:
      labels:
        app: my-react
    spec:
      containers:
      - name: myapp-container
        image: princenoble/ui-dev:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
