apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-react
  template:
    metadata:
      labels:
        app: m-react
    spec:
      containers:
      - name: myapp-container
        image: princenoble/ui-dev:1.0
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: m-service
spec:
  selector:
    app: m-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
